### PR TITLE
separate high and low level interfaces.

### PR DESCRIPTION
**Pull request by dominictarr**
This pull request separates the high and low level interfaces.
This means that the high level interface (and the tests) can be reused in another module that exposes the same low level interface. Also, the low level interface can be used directly.

The most significant change, apart from that was to make the low level interface fully deterministic,
low level keypair functions now throw if they are not provided with a seed. randomness is managed in the high level interface only.

this gets us closer to: #97 my plan is to redo the node-sodium bindings so that they are closer to the c interface, and then the various nacl libraries can all be consistent, and well tested.

### CODE REVIEW

**Comment by dominictarr** [comment]
I havn't been able to get the browser tests to run, but not sure if that is my fault or not?

**Comment by dchest** [comment]
Thanks for PR! I like the idea of separation, as it can remove code duplication, however:

- I'd like to keep low-level interface internal, "undocumented". It's not a nice JavaScript API, it's a plan port from tweetnacl.c with some things changed because JS doesn't have pointers and pointer arithmetic≥

- The goal of TweetNaCl.js is to be as close as possible to the original C code for easy auditing (I even have [a diff here](http://tweetnacl.js.org/diff.html), which hasn't been updated for new versions though), so changing low-level API is out of question if we want to keep this property. That's also why it's written in this strange style and formatting.

I need to think about it more.

FIY, functions that require randomness, but don't have it already [throw error](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L18).

**Comment by dchest** [comment]
What is the issue with browser tests? Any error messages?

**Comment by dominictarr** [comment]
Okay, the browser sets passed when I didn't set the `NACL_SRC` variable.

I didn't realized this was ment to be 1:1 with the c version! that is very good,

I think there is a good reason to expose the C api, and a reason that the C api is like it is.
It is strange for a javascript interface to pass in a buffer that the result is mutated into,
but doing this way means that the crypto library doesn't need to do any memory allocations,
which sometimes have security implications (secret keys floating about in memory) and also performance problems. It might not have a measurable effect on crypto implemented in javascript, but memory allocations can really slow down C.

For example, something like https://github.com/dchest/nacl-stream-js or http://github.com/dominictarr/pull-box-stream would be better written to the C api, because then you could, for example, decrypt in place, writing the plaintext back into the same buffer as the ciphertext, and saving an allocation.
(you can also encrypt like that, but have to make sure the plaintext is written to a buffer with some space for the mac to go into. this might be accomplished via a buffer pool system, something like this https://gist.github.com/dominictarr/34026e5b64644bed11ba)

This is my motivation for this pull request - I like your high level api, but I want to use it with bindings to C nacl - and still have access to the proper low level C api for when performance really matters.
And also, to have a portable js or C version, like we do with crypto-browserify, but for a better library than openssl

Hmm, okay there are other ways we can deal with randombytes if you will accept separating the low and high parts. I can change this pull request if necessary.

**Comment by dchest** [comment]
Oh, I agree with you completely on allocations. In another project of mine, I even make sure it's possible to allocate nonce+counter once and reuse it for many encryptions:

```typescript
/**
 * Encrypt src with ChaCha20 stream generated for the given
 * 32-byte key and 8-byte (as in original implementation) or
 * 12-byte (as in RFC7539) nonce and write the result into dst and
 * return it.
 *
 * dst and src may be the same, but otherwise must not overlap.
 *
 * If nonce is 12 bytes, users should not generate more than 256 GiB
 * with the same key or nonce, otherwise the stream will repeat.
 * The function will throw error if counter overflows to avoid this.
 *
 * If nonce is 8 bytes, the output is practically unlimited (2^70 bytes,
 * which is more than a million petabytes). However, it is not recommended
 * to generate 8-byte nonces randomly, as the chance of collision is
 * high.
 *
 * Never use the same key and nonce to encrypt more than one message.
 *
 * If nonceInplaceCounterLength is not 0, nonce is assumed to be a 16-byte
 * array with stream counter in first nonceInplaceCounterLength bytes and
 * nonce in last remaining bytes. The counter will be incremented
 * inplace for each ChaCha block. This is useful if you need to encrypt
 * one stream of data in chunks.
 */
export function streamXOR(key: Uint8Array, nonce: Uint8Array,
    src: Uint8Array, dst: Uint8Array, nonceInplaceCounterLength = 0): Uint8Array {
```

However, the current TweetNaCl low-level API isn't what I'd like to see being "public". One big thing I'd change is that it should drop index arguments and switch to `.subarray(start, end)` everywhere if it needs slices of memory (this even looks like passing C pointers).

Here's my proposal, for the start: what if you design a proper low-level API, let's call it almost-low-level API :-), and then make a tiny layer translating TweetNaCl's ugly low-level API into this new API. I'll be happy to make sure it works if I change anything by sending pull requests to you.

**Comment by dominictarr** [comment]
Deal.

Okay so you must mean things like the apis like https://download.libsodium.org/doc/secret-key_cryptography/authenticated_encryption.html that take a message and a message length.
in javascript/node we have buffers or UInt8Arrays which bundle both of those into one object.

So, in cases where the C api is `message, message_length` (as pointers) that would just become `message` as a single buffer. This would affect `secretbox, box, sign, sign_detached` (and their `open/verify` functions) `hash`, `auth`. everything that takes variable sized arguments. functions that take fixed size arguments would be left alone.

**Comment by dchest** [comment]
Oh, yes, and length can go too. I was initially thinking about starting indexes, like in:

```javascript
function crypto_stream_salsa20_xor(c,cpos,m,mpos,b,n,k) {
```

which in C version is 

```c
int crypto_stream_salsa20(unsigned char *c, unsigned long long clen,
                          const unsigned char *n, const unsigned char *k);
```

without `cpos`, `mpos`. But yeah, length can be omitted too, since it can be derived from `Uint8Array`. Also, it's probably worth to use common JS convention for names, e.g. `streamSalsa20`?

**Comment by dominictarr** [comment]
Oh, wasn't thinking of even including those functions, is there really a reason to use `salsa20` directly if you have `secretbox`? I'm not really concerned about the naming style as long as it's a straightforward mapping from the C version. I'd lean towards keeping the underscores, it reminds people this is different to ordinary code this is serious business. maybe drop `crypto_` from the start of everything though, because that gets annoying.

**Comment by dchest** [comment]
They are useful sometimes, yes, e.g. to implement a "userland" random number generator.

Agree, underscores are fine then.

**Pull request closed without merging**
