### PR TITLE
Dual license PD and ISC, so that public ISC via npm is recognized.

### PR DESCRIPTION
**Pull request by tracker1**
@dchest

* Added ISC license, and related comment in package.json... ISC is the most permissive, least verbose recognized license.
* Added COPYING.txt as advised, recognizing public domain dedication

This should satisfy the need for a license in upstream use, as well as keeping public domain dedication for derivative works.

I came across the licensing issue in my workplace via `phatomjs -> request -> http-signature -> sshpk -> tweetnacl` and am sure others have had a similar issue with an *unlicensed* usage.

### CODE REVIEW

**Comment by tracker1** [comment]
Maybe the public domain in copying.txt, then have the `package.json` license be:

    "license" : "SEE LICENSE IN COPYING.txt"

Would you consider changing to ISC?  It's pretty much the same level of permissiveness as CC0/PD, but at least is a "license" ... legally, it's still copyrighted automatically, and one cannot waive those rights except by license... even a license that does waive all rights on the work and derivatives... at least that's how it's been explained to me in the past.

I just need `phatomjs` for testing, which depends on `request`, which depends on `http-signature`, which depends on `sshpk` which, finally depends on this module... which is being denied for not having a license associated, or some such b.s. such is the down side of working at a large financial institution.

**Comment by tracker1** [comment]
@dchest How about this?

**Comment by dchest** [comment]
>Would you consider changing to ISC? It's pretty much the same level of permissiveness as CC0/PD, but at least is a "license" ... legally, it's still copyrighted automatically, and one cannot waive those rights except by license... even a license that does waive all rights on the work and derivatives... at least that's how it's been explained to me in the past.

That's not true. You have certain copyrights after creating a work. You can *license* these rights or *dedicate them to public domain*. Public domain dedication is not licensing.

As I said, I can put any license to my work of porting the code and creating high-level code, but the original work, which TweetNaCl.js is a derivative of, is still under public domain — with a statement on its home page:

> TweetNaCl is a self-contained public-domain C library, so it can easily be integrated into applications.

Thus your legal department, if they find this out will still be left with handing "public domain".

> "license" : "SEE LICENSE IN COPYING.txt"

I can do this, this will also solve npm warning.

**Comment by tracker1** [comment]
@dchest sorry, updated my comment with the PR... would dual-licensing as described in the PR work?

**Comment by anri-asaturov** [comment]
I wonder if one can fork a repo as a private person and then change the license in his fork to whatever the legal team wants and use that fork.

**Comment by tracker1** [comment]
That would require going through and updating a chain of 4 upstream dependencies...

**Comment by tracker1** [comment]
It's not impossible, walked through that on a deeply nested bug a couple years ago, but it wasn't fun.

**Comment by anri-asaturov** [comment]
4? Upstream update can be automated (git pull? :-D)

**Comment by tracker1** [comment]
@anri-asaturov upstream npm modules?

**Comment by dchest** [comment]
@anri-asaturov probably, you can fool your legal team with a fork, but the original problem is not solved: if they don't want public domain code, the original work is still in public domain, and thus they don't work your derivative. This is why it's pointless for me to dual-license it.

**Comment by tracker1** [comment]
@dchest honestly, I'm not sure if it's that it's public domain, or that npm doesn't recognize the license, so it shows up as no license... in either case, they probably didn't dig deeper, and I'm several layers removed from the decision makers on this...  part of this is speculation.. my guess is a permissive license (dual license) would be enough to get through this for myself, and most others... I don't think they've actually looked at it as far as I have.

**Comment by tracker1** [comment]
**I** get it... it's stupid, and they should have let it through, in all reality... this isn't even for redistribution, it's for an automated testing tool on a project...

**Comment by dchest** [comment]
Let's try this:

https://github.com/dchest/tweetnacl-js/commit/cd9f8e4230691e581eec6e12a006dacf8b753b94

if you're okay with this, I'll publish to npm.

**Comment by tracker1** [comment]
I'm willing to give it a try.. :-)

**Comment by dchest** [comment]
Good, published v0.14.1. Please let us know how it goes :)

**Pull request closed without merging**
